### ISSUE TITLE
Not really fixed the bypass method I founded

### ISSUE THREAD

**Issue by AnythingMayBe** [Rancio777/Linux-Minecraft-Screenshare-Tool#2]
Hello,

Sorry to say that, but I surely misspeak in my last issue.
I want you to write results in some variables, not files.
I did that script for bypassing your tool easily, https://github.com/AnythingMayBe/Linux-Screenshare-Bypass, but it's in Python, sorry, I don't really know how to use bash.

The main issue about that is we can easily edit the file, and knowing most users have the administrator permission, you probably can't modify permissions. You still can try to check the hash of the file and detect if that's edited after that, but I really don't recommend that, because you lose everything in your scan.

Best regards,
- AnythingMaybe

**Comment by bacanoicua** [comment]
como rompes las bolas

**Comment by Hugytor09YT** [comment]
la tuya por si acaso

**Comment by RRancio** [comment]
please die omfg

**Comment by AnythingMayBe** [comment]
I've already thought about it :)
